# Generated by Django 3.1.4 on 2021-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('option', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.FloatField(max_length=7)),
            ],
        ),
    ]
