# Generated by Django 3.1.4 on 2021-03-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('READY', 'READY'), ('CANCELED', 'CANCELED')], max_length=255)),
                ('consume_location', models.CharField(choices=[('TAKEAWAY', 'TAKEAWAY'), ('INSHOP', 'INSHOP')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('units', models.IntegerField(default=1)),
                ('id_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
